Fix 'PredictedBullet' could not be found
Assets\FishyEOSSamples\EOS Lobby\RigidbodyPredictionNewInput\RigidbodyPredictionNewInput.cs(231,17): error CS0246: The type or namespace name 'PredictedBullet' could not be found (are you missing a using directive or an assembly reference?)